name       : simplenote
version    : 1.0.6
release    : 1
source     :
    - https://github.com/Automattic/simplenote-electron/releases/download/v1.0.6/simplenote-1.0.6.deb : b2f644025c1bf3a9c431d417063ba5f954f3f194590ab36cd3c1e7b55ccc3c97
license    : GPL-2.0
component  : office
summary    : SimpleNote Electron Application
extract    : no
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(x11)
    - pkgconfig(xcursor)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
description: |
    The simplest way to keep notes.
    SimpleNote Electron Application
install    : |
    ar xf $sources/simplenote-${version}.deb
    mkdir root
    tar xf data.tar.gz -C root
    install -D -d -m 00755 $installdir/usr/bin
    cp -Rv root/* $installdir/.
    ln -sv ../share/simplenote/simplenote $installdir/usr/bin/simplenote
