name       : simplenote
version    : 1.6.0
release    : 19
source     :
    - https://github.com/Automattic/simplenote-electron/releases/download/v1.6.0/Simplenote-linux-1.6.0-amd64.deb : 84995f644f9a27ed7985702cf8028860aa325ec0f0dc363c17b4f26958c51f06
license    : GPL-2.0-or-later
component  : office.notes
summary    : The simplest way to keep notes.
description: |
    A Simplenote React app packaged in Electron.
extract    : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
install    : |
    ar xf $sources/Simplenote-linux-${version}-amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
    install -Ddm00755 $installdir/usr/bin
    cp -Rv root/usr/* $installdir/usr
    cp -Rv root/opt/* $installdir/usr/share
    ln -sv ../share/Simplenote/simplenote $installdir/usr/bin/simplenote
    install -Dm00644 $pkgfiles/simplenote.desktop $installdir/usr/share/applications/simplenote.desktop
