name       : simplenote
version    : 1.1.6
release    : 10
source     :
    - https://github.com/Automattic/simplenote-electron/releases/download/v1.1.6/simplenote_1.1.6_amd64.deb : d48d6a56beace13ca0c82e1bf540360685e3685bb29855dc6dc401c485449c4c
license    : GPL-2.0-or-later
component  : office.notes
summary    : The simplest way to keep notes.
description: |
    A Simplenote React app packaged in Electron.
extract    : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
install    : |
    ar xf $sources/simplenote_${version}_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root

    mv root/opt/Simplenote root/usr/share/simplenote
    rm -d root/opt/
    sed -i 's:/opt/Simplenote/::g' root/usr/share/applications/simplenote.desktop

    install -D -d -m 00755 $installdir/usr/bin
    cp -Rv root/* $installdir/.
    ln -sv /usr/share/simplenote/simplenote $installdir/usr/bin/simplenote
