name       : simplenote
version    : 1.9.0
release    : 21
source     :
    - https://github.com/Automattic/simplenote-electron/releases/download/v1.9.0/Simplenote-linux-1.9.0-amd64.deb : 396e0a794504799e5318a685f10de6c418c78b66880d297b1f0bdf5715b6d951
license    : GPL-2.0-or-later
component  : office.notes
summary    : The simplest way to keep notes.
description: |
    A Simplenote React app packaged in Electron.
extract    : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
setup      : |
    ar xf $sources/Simplenote-linux-${version}-amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
install    : |
    install -Ddm00755 $installdir/usr/bin
    cp -Rv root/usr/* $installdir/usr
    cp -Rv root/opt/* $installdir/usr/share
    ln -sv ../share/Simplenote/simplenote $installdir/usr/bin/simplenote
    install -Dm00644 $pkgfiles/simplenote.desktop $installdir/usr/share/applications/simplenote.desktop
