name       : simplenote
version    : 1.21.1
release    : 29
source     :
    - https://github.com/Automattic/simplenote-electron/releases/download/v1.21.1/Simplenote-linux-1.21.1-amd64.deb : 1d4d87984fe772286389680c498287c5dd0ab602a442deab7839fb139a401d03
homepage   : https://simplenote.com/
license    : GPL-2.0-only
component  : office.notes
summary    : The simplest way to keep notes
description: |
    A Simplenote React app packaged in Electron.
extract    : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
setup      : |
    ar xf $sources/Simplenote-linux-${version}-amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
install    : |
    install -dm00755 $installdir/usr/bin
    cp -Rv root/usr/* $installdir/usr
    cp -Rv root/opt/* $installdir/usr/share
    ln -sv ../share/Simplenote/simplenote $installdir/usr/bin/simplenote
    install -Dm00644 $pkgfiles/simplenote.desktop $installdir/usr/share/applications/simplenote.desktop
