name       : simplenote
version    : 2.2.0
release    : 32
source     :
    - https://github.com/Automattic/simplenote-electron/releases/download/v2.2.0/Simplenote-linux-2.2.0-amd64.deb : dbc52a2783a5d28f0692f55a8705f894774360ad459b39bed0c80012a0036b88
homepage   : https://simplenote.com/
license    : GPL-2.0-only
component  : office.notes
summary    : The simplest way to keep notes
description: |
    A Simplenote React app packaged in Electron.
extract    : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
setup      : |
    ar xf $sources/Simplenote-linux-${version}-amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
install    : |
    install -dm00755 $installdir/usr/bin
    cp -Rv root/usr/* $installdir/usr
    cp -Rv root/opt/* $installdir/usr/share
    ln -sv ../share/Simplenote/simplenote $installdir/usr/bin/simplenote
    install -Dm00644 $pkgfiles/simplenote.desktop $installdir/usr/share/applications/simplenote.desktop
