name       : simplenote
version    : 1.14.0
release    : 24
source     :
    - https://github.com/Automattic/simplenote-electron/releases/download/v1.14.0/Simplenote-linux-1.14.0-amd64.deb : b133f48a4673fc958c33163ccf51eb5a826331bd63655bab47cd011483ebc1d0
homepage   : https://simplenote.com/
license    : GPL-2.0-or-later
component  : office.notes
summary    : The simplest way to keep notes.
description: |
    A Simplenote React app packaged in Electron.
extract    : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
setup      : |
    ar xf $sources/Simplenote-linux-${version}-amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
install    : |
    install -Ddm00755 $installdir/usr/bin
    cp -Rv root/usr/* $installdir/usr
    cp -Rv root/opt/* $installdir/usr/share
    ln -sv ../share/Simplenote/simplenote $installdir/usr/bin/simplenote
    install -Dm00644 $pkgfiles/simplenote.desktop $installdir/usr/share/applications/simplenote.desktop
