name       : simplenote
version    : 1.1.3
release    : 9
source     :
    - https://github.com/Automattic/simplenote-electron/releases/download/v1.1.3/Simplenote-linux-1.1.3.deb : a26f0515922c71dcda289ec47b07b129e35748d677410a17d89d21e6e846cba7
license    : GPL-2.0
component  : office.notes
summary    : The simplest way to keep notes.
description: |
    A Simplenote React app packaged in Electron.
extract    : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
install    : |
    ar xf $sources/Simplenote-linux-${version}.deb
    mkdir root
    tar xf data.tar.gz -C root
    install -D -d -m 00755 $installdir/usr/bin
    cp -Rv root/* $installdir/.
    ln -sv ../share/simplenote/simplenote $installdir/usr/bin/simplenote
