name       : simplenote
version    : 1.3.2
release    : 13
source     :
    - https://github.com/Automattic/simplenote-electron/releases/download/v1.3.2/Simplenote-linux-1.3.2-amd64.deb : f4bc3ef29bfd63d0aae3f58fd272b7b28a46ced673e8369a8771bc3b05161491
license    : GPL-2.0-or-later
component  : office.notes
summary    : The simplest way to keep notes.
description: |
    A Simplenote React app packaged in Electron.
extract    : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
install    : |
    ar xf $sources/Simplenote-linux-${version}-amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
    install -D -d -m 00755 $installdir/usr/bin
    cp -Rv root/usr/* $installdir/usr
    cp -Rv root/opt/* $installdir/usr/share
    ln -sv ../share/Simplenote/simplenote $installdir/usr/bin/simplenote
    install -Dm00644 $pkgfiles/simplenote.desktop $installdir/usr/share/applications/simplenote.desktop
